[programs.localnet]
sol_nft_staking = "UPoahzo6P5XpdCZx4GbwL5JVcPNdD6naXmBQpRLwNH7"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/user/.config/solana/id.json"
# [provider]
# cluster = "localnet"
# wallet = "/home/aaron/.config/solana/id.json"

# [test]
# # Clone the metadata program and the executable account associated with it
# # for use in integration tests
# clone = [
#   {address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"}, 
#   {address = "PwDiXFxQsGra4sFFTT8r1QWRMd4vfumiWC1jfWNfdYT"}
# ]
# validator = {url = "mainnet-beta"}

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"


